sudo: required
dist: bionic
job:
  - arch: amd64
  - virt: lxd
    group: edge
    arch: arm64-graviton2
language: python
install: true

services:
  - docker

script: true

after_success:
  - echo $TRAVIS_REPO_SLUG
  - export TRAVIS_REPO_SLUG=pshub/cer
  - $TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}_arm64
  - echo $TRAVIS_REPO_SLUG
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $TRAVIS_REPO_SLUG .;
    docker login -u=pshub -p=dockerhubDOCKERHUB1#;
    docker push $TRAVIS_REPO_SLUG;
    fi
